version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: social_postgres
    environment:
      POSTGRES_USER: social_user
      POSTGRES_PASSWORD: social_password
      POSTGRES_DB: social_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social_user -d social_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: